version: '3.8'

services:
  orthanc-storage-1:
    image: jodogne/orthanc
    container_name: orthanc-storage-1
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - ./orthanc_storage_1.json:/etc/orthanc/orthanc.json
    networks:
      - orthanc-network
    restart: unless-stopped

  orthanc-storage-2:
    image: jodogne/orthanc
    container_name: orthanc-storage-2
    ports:
      - "8043:8042"
      - "4243:4242"
    volumes:
      - ./orthanc_storage_2.json:/etc/orthanc/orthanc.json
    networks:
      - orthanc-network
    restart: unless-stopped

  orthanc-probe:
    image: jodogne/orthanc
    container_name: orthanc-probe
    ports:
      - "8052:8042"
      - "4252:4242"
    volumes:
      - ./orthanc_probe.json:/etc/orthanc/orthanc.json
    networks:
      - orthanc-network
    restart: unless-stopped

  dicom-middleware-cli:
    build: .
    container_name: dicom-middleware-cli
    networks:
      - orthanc-network
    ports:
      - "11113:11113"
    entrypoint: ["python", "main.py"]

  dicom-middleware-api:
    build: .
    container_name: dicom-middleware-api
    ports:
      - "5000:5000"
    volumes:
      - ./temp_dicom_files:/app/temp_dicom_files
    networks:
      - orthanc-network
    entrypoint: ["python", "app.py"]

networks:
  orthanc-network:
    driver: bridge
